export const TILE = {
	EMPTY: 0,
	WALL_SQUARE: 10,
	WALL_DIAGONAL_BOTTOM_LEFT: 11,
	WALL_DIAGONAL_TOP_LEFT: 12,
	WALL_DIAGONAL_TOP_RIGHT: 13,
	WALL_DIAGONAL_BOTTOM_RIGHT: 14,
	FLOOR_NEUTRAL: 20,
	FLAG_RED: 30,
	FLAG_BLUE: 40,
	SPEEDPAD_NEUTRAL: 50,
	POWERUP: 60,
	POWERUP_JUKE_JUICE: 61,
	POWERUP_ROLLING_BOMB: 62,
	POWERUP_TAGPRO: 63,
	POWERUP_TOP_SPEED: 64,
	SPIKE: 70,
	BUTTON: 80,
	GATE_OPEN: 90,
	GATE_CLOSED: 91,
	GATE_RED: 92,
	GATE_BLUE: 93,
	BOMB: 100,
	FLOOR_RED: 110,
	FLOOR_BLUE: 120,
	PORTAL_ENTRY: 130,
	PORTAL_EXIT: 131,
	SPEEDPAD_RED: 140,
	SPEEDPAD_BLUE: 150,
	FLAG_NEUTRAL: 160,
	FLAG_TEMPORARY: 161, // just a dummy, cannot occur on maps
	ENDZONE_RED: 170,
	ENDZONE_BLUE: 180,
	FLAG_POTATO_RED: 190,
	FLAG_POTATO_BLUE: 200,
	FLAG_POTATO_NEUTRAL: 210,
	MARSBALL: 211, // just a dummy, cannot occur on maps
	GRAVITYWELL: 220,
};

export const TEAM = {
	NONE: 0,
	RED: 1,
	BLUE: 2,
};

export const FLAG = {
	NONE: 0,
	OPPONENT: 1,
	OPPONENT_POTATO: 2,
	NEUTRAL: 3,
	NEUTRAL_POTATO: 4,
	TEMPORARY: 5,
};

export const POWERS = {
	NONE: 0,
	JUKE_JUICE: 1,
	ROLLING_BOMB: 2,
	TAGPRO: 4,
	TOP_SPEED: 8,
};

export const BUTTON = {
	NONE: 0,
	BUTTONS_ONLY: 1,
	BUTTONS_AND_GATES: 2,
};
